apiVersion: v1
kind: Service
metadata:
  name: tourism-backend-service
spec:
  selector:
    app: tourism-backend
  ports:
    - protocol: TCP
      port: 80          # Service Port
      targetPort: 8080  # Container Port
      nodePort: 30007   # Fixed NodePort (optional, range: 30000-32767)
  type: NodePort
